### ISSUE TITLE
Reselect like functionality

### ISSUE THREAD

**Issue by kostaa** [marcglasberg/provider_for_redux#1]
I like your approach and considering replacing the 'plain vanilla' Redux that I am currently using with your async_redux. I have a fairly complex domain model however that gets assembled by using [reselect](https://pub.dev/packages/reselect) library selectors. I was wondering if there is a way to achieve the same behaviour (caching and reusing already cached data) with the ReduxSelector?

I know that I could still use the reselect after moving to the async_redux but It would be great  to have this provided by the ReduxSelector so I could drop all the ViewModels that are required by the [flutter_redux](https://pub.dev/packages/flutter_redux) StoreConnector.

**Comment by marcglasberg** [comment]
I'm not sure I understand your question. When you move to async_redux you have 3 options:

1) You can use the same `ViewModel`s you're already using with flutter_redux (with the `converter` parameter of the `StoreConnector`).
2) You can use the somewhat more streamlined `ViewModel`s that extend `BaseModel`, specific to async_redux (with the `model` parameter).
3) You can use `ReduxSelector` and `Provider` to replace the `StoreConnector` altogether.

You should probably start with (1) above, because it will work with what you already have, and slowly migrate to (2) or (3).

In all 3 cases you must define a model using any piece of the state directly, or by using selectors, with or without reselect.

So, yes, you can achieve the same behavior (caching and reusing already cached data) with the ReduxSelector and the reselect libray. Just define your model by querying the selector:

    selector: (context, state) => mySelector(state)

The only requirement is that the selector returns some object that can be compared with the previous one to see if the state changed. Or it must be wrapped in some object that can do that.

If I didn't answer or understood your question, feel free to give me some more detail.

**Comment by kostaa** [comment]
Actually while refactoring I have done (more or less) what you described above. 
I like it a lot. It simplifies things greatly and reduces the mental overhead - many thanks!
